### ISSUE TITLE
PlatformException at com.appsflyer.internal.AFa1aSDK.start

### ISSUE THREAD

**Issue by dmitry-fbm** [AppsFlyerSDK/appsflyer-android-app#19]
Cannot reproduce this locally but getting massive amount of errors from production apps since last release. There was no relevant code changes, the only difference I can think of is upgrade to Flutter 3.3.8.

```
PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
 	at com.appsflyer.internal.AFa1aSDK.start(Unknown Source:124)
 	at com.appsflyer.internal.AFa1aSDK.start(Unknown Source:19)
 	at com.appsflyer.internal.AFa1aSDK.start(Unknown Source:11)
 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.initSdk(Unknown Source:130)
 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.onMethodCall(Unknown Source:536)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:20)
 	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
 	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:226)
 	at android.os.Looper.loop(Looper.java:313)
 	at android.app.ActivityThread.main(ActivityThread.java:8751)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) )
```

**Comment by dmitry-fbm** [comment]
Sorry, probably posted into wrong branch - had to be appsflyer-flutter-plugin.

**Comment by dmitry-fbm** [comment]
This can be closed, doesn't happen in newer versions anymore.
