### ISSUE TITLE
ANR com.appsflyer.internal.AFb1xSDK$AFa1xSDK.run 

### ISSUE THREAD

**Issue by halysongoncalves** [AppsFlyerSDK/appsflyer-android-app#22]
I have many ANR on TCL TV Android

 at com.appsflyer.internal.AFb1xSDK.values
  at com.appsflyer.internal.AFb1xSDK.values
  at com.appsflyer.internal.AFb1xSDK.AFKeystoreWrapper
  at com.appsflyer.internal.AFb1xSDK.AFKeystoreWrapper
  at com.appsflyer.internal.AFb1xSDK$AFa1xSDK.run
  at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:458)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

![Captura de Tela 2023-03-02 às 15 45 05](https://user-images.githubusercontent.com/5872045/222522719-e1680a2c-d95d-4fb9-bf4d-2506d0c9a1be.png)
![Captura de Tela 2023-03-02 às 15 45 19](https://user-images.githubusercontent.com/5872045/222522729-f6361c5e-5d62-4026-b05b-353019f2139e.png)
![Captura de Tela 2023-03-02 às 15 45 24](https://user-images.githubusercontent.com/5872045/222522733-b5438625-6f4f-46c6-9aa1-66028e0abb0d.png)

**Comment by ariko-sp** [comment]
same

**Comment by ChrisElliotUK** [comment]
same

**Comment by ThushalIntervest** [comment]
same here 

```
Fatal Exception: java.lang.Error: java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1xSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1xSDK$$>
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by kthangtd** [comment]
Same error:
```
                 Error while sending request to server: java.lang.ExceptionInInitializerError
                 java.lang.ExceptionInInitializerError
                 	at com.appsflyer.internal.AFe1hSDK.AFKeystoreWrapper(:143)
                 	at com.appsflyer.internal.AFe1qSDK.values(:113)
                 	at com.appsflyer.internal.AFe1pSDK.values(:81)
                 	at com.appsflyer.internal.AFe1qSDK.valueOf(:76)
                 	at com.appsflyer.internal.AFd1aSDK.AFKeystoreWrapper(:117)
                 	at com.appsflyer.internal.AFd1fSDK$3.run(:110)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
                 Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
                 	at com.appsflyer.internal.AFb1hSDK.<clinit>(:282)
                 	at com.appsflyer.internal.AFe1hSDK.AFKeystoreWrapper(:143) 
                 	at com.appsflyer.internal.AFe1qSDK.values(:113) 
                 	at com.appsflyer.internal.AFe1pSDK.values(:81) 
                 	at com.appsflyer.internal.AFe1qSDK.valueOf(:76) 
                 	at com.appsflyer.internal.AFd1aSDK.AFKeystoreWrapper(:117) 
                 	at com.appsflyer.internal.AFd1fSDK$3.run(:110) 
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                 	at java.lang.Thread.run(Thread.java:1012) 
                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
                 	at java.io.DataInputStream.readFully(DataInputStream.java:203)
                 	at java.io.DataInputStream.readFully(DataInputStream.java:173)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.appsflyer.internal.AFb1hSDK.<clinit>
```
