### ISSUE TITLE
ConcurrentModificationException from within sdk

### ISSUE THREAD

**Issue by rajatsharma16** [AppsFlyerSDK/appsflyer-android-app#24]
Per firebase: This issue has 1 crash event affecting 1 user in last 90 days.

This was observed in the launch flow of the app. Should be noted that these methods did fire (had placed my logs in these)

- `AppsFlyerRequestListener.onSuccess`
- `AppsFlyerConversionListener.onConversionDataSuccess`

**SDK version**: com.appsflyer:af-android-sdk:6.12.2
```
Fatal Exception: java.util.ConcurrentModificationException:
       at android.util.ArrayMap.binarySearchHashes(ArrayMap.java:121)
       at android.util.ArrayMap.indexOf(ArrayMap.java:137)
       at android.util.ArrayMap.indexOfKey(ArrayMap.java:418)
       at android.util.ArrayMap.get(ArrayMap.java:468)
       at android.os.BaseBundle.getString(BaseBundle.java:1161)
       at android.content.Intent.getStringExtra(Intent.java:8552)
       at android.app.Activity.getReferrer(Activity.java:6115)
       at com.appsflyer.internal.AFb1nSDK.AFInAppEventType(:34)
       at com.appsflyer.internal.AFf1ySDK.AFKeystoreWrapper(:68)
       at com.appsflyer.internal.AFf1ySDK.AFInAppEventParameterName(:40)
       at com.appsflyer.internal.AFb1jSDK.valueOf(:112)
```

**Comment by rajatsharma16** [comment]
Support asked to upgrade to `com.appsflyer:af-android-sdk:6.12.3`. So closing this for now here.
