### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by vivian688** [AppsFlyerSDK/appsflyer-android-app#25]
I saw a user using Android encounter this crash on the firebase console.
AppsFlyerSDK Version: 6.12.2
Rom: Infinix/X6826C-OP
Android Version: Android 12

1	java.lang.RuntimeException:java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
2	com.appsflyer.internal.AFa1wSDK.<clinit>(:275)
3	......
4	Caused by:
5	java.lang.NullPointerException:Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
6	java.io.DataInputStream.readFully(DataInputStream.java:203)
7	java.io.DataInputStream.readFully(DataInputStream.java:173)
8	java.lang.reflect.Method.invoke(Native Method)
9	com.appsflyer.internal.AFa1wSDK.<clinit>(:2411)
10	com.appsflyer.internal.AFc1vSDK.AFKeystoreWrapper(:143)
11	com.appsflyer.internal.AFd1rSDK.AFKeystoreWrapper(:65)
12	com.appsflyer.internal.AFd1vSDK.values(:113)
13	com.appsflyer.internal.AFc1gSDK$1.run(:109)
14	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
15	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
16	java.lang.Thread.run(Thread.java:1012)

**Comment by jinyaocn** [comment]
same

**Comment by vkomysh-vicman** [comment]
Same crashes (from Crashlytics) on latest AppsFlyerSDK Version: 6.13.0 (on 6.12.4 worked fine)
All problem users have expired subscription.
I suppose the reason is the library `com.appsflyer:purchase-connector:2.0.1`

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
       at java.io.DataInputStream.readFully(DataInputStream.java:203)
       at java.io.DataInputStream.readFully(DataInputStream.java:173)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.appsflyer.internal.AFc1fSDK.<clinit>(:2189)
       at com.appsflyer.internal.AFg1zSDK.values(:170)
       at com.appsflyer.internal.AFf1pSDK.AFInAppEventType(:122)
       at com.appsflyer.internal.AFf1pSDK.valueOf(:82)
       at com.appsflyer.internal.AFf1tSDK.AFInAppEventParameterName(:25)
       at com.appsflyer.internal.AFe1dSDK$4.run(:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```
